# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LaserLineAlignment

# Build rule for target.
LaserLineAlignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaserLineAlignment
.PHONY : LaserLineAlignment

# fast build rule for target.
LaserLineAlignment/fast:
	$(MAKE) -f CMakeFiles/LaserLineAlignment.dir/build.make CMakeFiles/LaserLineAlignment.dir/build
.PHONY : LaserLineAlignment/fast

#=============================================================================
# Target rules for targets named calculated_laser_line

# Build rule for target.
calculated_laser_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calculated_laser_line
.PHONY : calculated_laser_line

# fast build rule for target.
calculated_laser_line/fast:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/build
.PHONY : calculated_laser_line/fast

#=============================================================================
# Target rules for targets named LaserDotAlignment

# Build rule for target.
LaserDotAlignment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaserDotAlignment
.PHONY : LaserDotAlignment

# fast build rule for target.
LaserDotAlignment/fast:
	$(MAKE) -f CMakeFiles/LaserDotAlignment.dir/build.make CMakeFiles/LaserDotAlignment.dir/build
.PHONY : LaserDotAlignment/fast

LaserDotAlignment.o: LaserDotAlignment.cpp.o

.PHONY : LaserDotAlignment.o

# target to build an object file
LaserDotAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/LaserDotAlignment.dir/build.make CMakeFiles/LaserDotAlignment.dir/LaserDotAlignment.cpp.o
.PHONY : LaserDotAlignment.cpp.o

LaserDotAlignment.i: LaserDotAlignment.cpp.i

.PHONY : LaserDotAlignment.i

# target to preprocess a source file
LaserDotAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/LaserDotAlignment.dir/build.make CMakeFiles/LaserDotAlignment.dir/LaserDotAlignment.cpp.i
.PHONY : LaserDotAlignment.cpp.i

LaserDotAlignment.s: LaserDotAlignment.cpp.s

.PHONY : LaserDotAlignment.s

# target to generate assembly for a file
LaserDotAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/LaserDotAlignment.dir/build.make CMakeFiles/LaserDotAlignment.dir/LaserDotAlignment.cpp.s
.PHONY : LaserDotAlignment.cpp.s

LaserLineAlignment.o: LaserLineAlignment.cpp.o

.PHONY : LaserLineAlignment.o

# target to build an object file
LaserLineAlignment.cpp.o:
	$(MAKE) -f CMakeFiles/LaserLineAlignment.dir/build.make CMakeFiles/LaserLineAlignment.dir/LaserLineAlignment.cpp.o
.PHONY : LaserLineAlignment.cpp.o

LaserLineAlignment.i: LaserLineAlignment.cpp.i

.PHONY : LaserLineAlignment.i

# target to preprocess a source file
LaserLineAlignment.cpp.i:
	$(MAKE) -f CMakeFiles/LaserLineAlignment.dir/build.make CMakeFiles/LaserLineAlignment.dir/LaserLineAlignment.cpp.i
.PHONY : LaserLineAlignment.cpp.i

LaserLineAlignment.s: LaserLineAlignment.cpp.s

.PHONY : LaserLineAlignment.s

# target to generate assembly for a file
LaserLineAlignment.cpp.s:
	$(MAKE) -f CMakeFiles/LaserLineAlignment.dir/build.make CMakeFiles/LaserLineAlignment.dir/LaserLineAlignment.cpp.s
.PHONY : LaserLineAlignment.cpp.s

calculated_laser_line.o: calculated_laser_line.cpp.o

.PHONY : calculated_laser_line.o

# target to build an object file
calculated_laser_line.cpp.o:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.o
.PHONY : calculated_laser_line.cpp.o

calculated_laser_line.i: calculated_laser_line.cpp.i

.PHONY : calculated_laser_line.i

# target to preprocess a source file
calculated_laser_line.cpp.i:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.i
.PHONY : calculated_laser_line.cpp.i

calculated_laser_line.s: calculated_laser_line.cpp.s

.PHONY : calculated_laser_line.s

# target to generate assembly for a file
calculated_laser_line.cpp.s:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.s
.PHONY : calculated_laser_line.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... LaserLineAlignment"
	@echo "... calculated_laser_line"
	@echo "... LaserDotAlignment"
	@echo "... LaserDotAlignment.o"
	@echo "... LaserDotAlignment.i"
	@echo "... LaserDotAlignment.s"
	@echo "... LaserLineAlignment.o"
	@echo "... LaserLineAlignment.i"
	@echo "... LaserLineAlignment.s"
	@echo "... calculated_laser_line.o"
	@echo "... calculated_laser_line.i"
	@echo "... calculated_laser_line.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

