# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LaserDotMeasure_Origin

# Build rule for target.
LaserDotMeasure_Origin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaserDotMeasure_Origin
.PHONY : LaserDotMeasure_Origin

# fast build rule for target.
LaserDotMeasure_Origin/fast:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Origin.dir/build.make CMakeFiles/LaserDotMeasure_Origin.dir/build
.PHONY : LaserDotMeasure_Origin/fast

#=============================================================================
# Target rules for targets named LaserDotMeasure_Pixel

# Build rule for target.
LaserDotMeasure_Pixel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LaserDotMeasure_Pixel
.PHONY : LaserDotMeasure_Pixel

# fast build rule for target.
LaserDotMeasure_Pixel/fast:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Pixel.dir/build.make CMakeFiles/LaserDotMeasure_Pixel.dir/build
.PHONY : LaserDotMeasure_Pixel/fast

LaserDotMeasure_Origin.o: LaserDotMeasure_Origin.cpp.o

.PHONY : LaserDotMeasure_Origin.o

# target to build an object file
LaserDotMeasure_Origin.cpp.o:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Origin.dir/build.make CMakeFiles/LaserDotMeasure_Origin.dir/LaserDotMeasure_Origin.cpp.o
.PHONY : LaserDotMeasure_Origin.cpp.o

LaserDotMeasure_Origin.i: LaserDotMeasure_Origin.cpp.i

.PHONY : LaserDotMeasure_Origin.i

# target to preprocess a source file
LaserDotMeasure_Origin.cpp.i:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Origin.dir/build.make CMakeFiles/LaserDotMeasure_Origin.dir/LaserDotMeasure_Origin.cpp.i
.PHONY : LaserDotMeasure_Origin.cpp.i

LaserDotMeasure_Origin.s: LaserDotMeasure_Origin.cpp.s

.PHONY : LaserDotMeasure_Origin.s

# target to generate assembly for a file
LaserDotMeasure_Origin.cpp.s:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Origin.dir/build.make CMakeFiles/LaserDotMeasure_Origin.dir/LaserDotMeasure_Origin.cpp.s
.PHONY : LaserDotMeasure_Origin.cpp.s

LaserDotMeasure_Pixel.o: LaserDotMeasure_Pixel.cpp.o

.PHONY : LaserDotMeasure_Pixel.o

# target to build an object file
LaserDotMeasure_Pixel.cpp.o:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Pixel.dir/build.make CMakeFiles/LaserDotMeasure_Pixel.dir/LaserDotMeasure_Pixel.cpp.o
.PHONY : LaserDotMeasure_Pixel.cpp.o

LaserDotMeasure_Pixel.i: LaserDotMeasure_Pixel.cpp.i

.PHONY : LaserDotMeasure_Pixel.i

# target to preprocess a source file
LaserDotMeasure_Pixel.cpp.i:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Pixel.dir/build.make CMakeFiles/LaserDotMeasure_Pixel.dir/LaserDotMeasure_Pixel.cpp.i
.PHONY : LaserDotMeasure_Pixel.cpp.i

LaserDotMeasure_Pixel.s: LaserDotMeasure_Pixel.cpp.s

.PHONY : LaserDotMeasure_Pixel.s

# target to generate assembly for a file
LaserDotMeasure_Pixel.cpp.s:
	$(MAKE) -f CMakeFiles/LaserDotMeasure_Pixel.dir/build.make CMakeFiles/LaserDotMeasure_Pixel.dir/LaserDotMeasure_Pixel.cpp.s
.PHONY : LaserDotMeasure_Pixel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... LaserDotMeasure_Origin"
	@echo "... rebuild_cache"
	@echo "... LaserDotMeasure_Pixel"
	@echo "... LaserDotMeasure_Origin.o"
	@echo "... LaserDotMeasure_Origin.i"
	@echo "... LaserDotMeasure_Origin.s"
	@echo "... LaserDotMeasure_Pixel.o"
	@echo "... LaserDotMeasure_Pixel.i"
	@echo "... LaserDotMeasure_Pixel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

