# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lingbo/Documents/GitHub/AssemblyGuidanceTool

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lingbo/Documents/GitHub/AssemblyGuidanceTool/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calculated_laser_line

# Build rule for target.
calculated_laser_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calculated_laser_line
.PHONY : calculated_laser_line

# fast build rule for target.
calculated_laser_line/fast:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/build
.PHONY : calculated_laser_line/fast

#=============================================================================
# Target rules for targets named get_rvec_tvec

# Build rule for target.
get_rvec_tvec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 get_rvec_tvec
.PHONY : get_rvec_tvec

# fast build rule for target.
get_rvec_tvec/fast:
	$(MAKE) -f CMakeFiles/get_rvec_tvec.dir/build.make CMakeFiles/get_rvec_tvec.dir/build
.PHONY : get_rvec_tvec/fast

#=============================================================================
# Target rules for targets named AG_DEMO

# Build rule for target.
AG_DEMO: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AG_DEMO
.PHONY : AG_DEMO

# fast build rule for target.
AG_DEMO/fast:
	$(MAKE) -f CMakeFiles/AG_DEMO.dir/build.make CMakeFiles/AG_DEMO.dir/build
.PHONY : AG_DEMO/fast

#=============================================================================
# Target rules for targets named planes_intersection

# Build rule for target.
planes_intersection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 planes_intersection
.PHONY : planes_intersection

# fast build rule for target.
planes_intersection/fast:
	$(MAKE) -f CMakeFiles/planes_intersection.dir/build.make CMakeFiles/planes_intersection.dir/build
.PHONY : planes_intersection/fast

AG_DEMO.o: AG_DEMO.cpp.o

.PHONY : AG_DEMO.o

# target to build an object file
AG_DEMO.cpp.o:
	$(MAKE) -f CMakeFiles/AG_DEMO.dir/build.make CMakeFiles/AG_DEMO.dir/AG_DEMO.cpp.o
.PHONY : AG_DEMO.cpp.o

AG_DEMO.i: AG_DEMO.cpp.i

.PHONY : AG_DEMO.i

# target to preprocess a source file
AG_DEMO.cpp.i:
	$(MAKE) -f CMakeFiles/AG_DEMO.dir/build.make CMakeFiles/AG_DEMO.dir/AG_DEMO.cpp.i
.PHONY : AG_DEMO.cpp.i

AG_DEMO.s: AG_DEMO.cpp.s

.PHONY : AG_DEMO.s

# target to generate assembly for a file
AG_DEMO.cpp.s:
	$(MAKE) -f CMakeFiles/AG_DEMO.dir/build.make CMakeFiles/AG_DEMO.dir/AG_DEMO.cpp.s
.PHONY : AG_DEMO.cpp.s

calculated_laser_line.o: calculated_laser_line.cpp.o

.PHONY : calculated_laser_line.o

# target to build an object file
calculated_laser_line.cpp.o:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.o
.PHONY : calculated_laser_line.cpp.o

calculated_laser_line.i: calculated_laser_line.cpp.i

.PHONY : calculated_laser_line.i

# target to preprocess a source file
calculated_laser_line.cpp.i:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.i
.PHONY : calculated_laser_line.cpp.i

calculated_laser_line.s: calculated_laser_line.cpp.s

.PHONY : calculated_laser_line.s

# target to generate assembly for a file
calculated_laser_line.cpp.s:
	$(MAKE) -f CMakeFiles/calculated_laser_line.dir/build.make CMakeFiles/calculated_laser_line.dir/calculated_laser_line.cpp.s
.PHONY : calculated_laser_line.cpp.s

get_rvec_tvec.o: get_rvec_tvec.cpp.o

.PHONY : get_rvec_tvec.o

# target to build an object file
get_rvec_tvec.cpp.o:
	$(MAKE) -f CMakeFiles/get_rvec_tvec.dir/build.make CMakeFiles/get_rvec_tvec.dir/get_rvec_tvec.cpp.o
.PHONY : get_rvec_tvec.cpp.o

get_rvec_tvec.i: get_rvec_tvec.cpp.i

.PHONY : get_rvec_tvec.i

# target to preprocess a source file
get_rvec_tvec.cpp.i:
	$(MAKE) -f CMakeFiles/get_rvec_tvec.dir/build.make CMakeFiles/get_rvec_tvec.dir/get_rvec_tvec.cpp.i
.PHONY : get_rvec_tvec.cpp.i

get_rvec_tvec.s: get_rvec_tvec.cpp.s

.PHONY : get_rvec_tvec.s

# target to generate assembly for a file
get_rvec_tvec.cpp.s:
	$(MAKE) -f CMakeFiles/get_rvec_tvec.dir/build.make CMakeFiles/get_rvec_tvec.dir/get_rvec_tvec.cpp.s
.PHONY : get_rvec_tvec.cpp.s

planes_intersection.o: planes_intersection.cpp.o

.PHONY : planes_intersection.o

# target to build an object file
planes_intersection.cpp.o:
	$(MAKE) -f CMakeFiles/planes_intersection.dir/build.make CMakeFiles/planes_intersection.dir/planes_intersection.cpp.o
.PHONY : planes_intersection.cpp.o

planes_intersection.i: planes_intersection.cpp.i

.PHONY : planes_intersection.i

# target to preprocess a source file
planes_intersection.cpp.i:
	$(MAKE) -f CMakeFiles/planes_intersection.dir/build.make CMakeFiles/planes_intersection.dir/planes_intersection.cpp.i
.PHONY : planes_intersection.cpp.i

planes_intersection.s: planes_intersection.cpp.s

.PHONY : planes_intersection.s

# target to generate assembly for a file
planes_intersection.cpp.s:
	$(MAKE) -f CMakeFiles/planes_intersection.dir/build.make CMakeFiles/planes_intersection.dir/planes_intersection.cpp.s
.PHONY : planes_intersection.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... calculated_laser_line"
	@echo "... edit_cache"
	@echo "... get_rvec_tvec"
	@echo "... rebuild_cache"
	@echo "... AG_DEMO"
	@echo "... planes_intersection"
	@echo "... AG_DEMO.o"
	@echo "... AG_DEMO.i"
	@echo "... AG_DEMO.s"
	@echo "... calculated_laser_line.o"
	@echo "... calculated_laser_line.i"
	@echo "... calculated_laser_line.s"
	@echo "... get_rvec_tvec.o"
	@echo "... get_rvec_tvec.i"
	@echo "... get_rvec_tvec.s"
	@echo "... planes_intersection.o"
	@echo "... planes_intersection.i"
	@echo "... planes_intersection.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

